version: '3.3'

services:

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  web:
    build:
      context: ./web
      args:
        POETRY_VERSION: "1.0.0"
        PROD_MODE: "false"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CORS_ORIGIN_WHITELIST=${CORS_ORIGIN_WHITELIST}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
    ports:
      - 8002:8002

volumes: 
  pgdata: