version: '3.3'

services:
  redis:
    image: "redis:alpine"

  celery:
    build:
      context: ./web
      args:
        POETRY_VERSION: "1.0.0"
        PROD_MODE: "false"
    command: celery -A app worker -l debug

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=no_mas_hambre
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes: 
  pgdata: