# Generated by Django 3.0.6 on 2020-06-22 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20200621_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_participantes', to='base.Organizacion', verbose_name='organización'),
        ),
    ]
