# Generated by Django 3.0.6 on 2020-06-23 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20200621_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comuna',
            name='region',
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64, verbose_name='nombre')),
                ('codigo', models.IntegerField(verbose_name='código')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincias', to='base.Region', verbose_name='región')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='provincia',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comunas', to='base.Provincia', verbose_name='provincia'),
            preserve_default=False,
        ),
    ]
