# Generated by Django 3.0.6 on 2020-06-29 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20200622_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoOrganizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64, unique=True, verbose_name='nombre')),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'tipo de organización',
                'verbose_name_plural': 'tipos de organización',
            },
        ),
        migrations.AddField(
            model_name='organizacion',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizaciones', to='base.TipoOrganizacion', verbose_name='tipo de organización'),
        ),
    ]
