# Generated by Django 3.0.6 on 2020-06-29 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20200629_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoContacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64, unique=True, verbose_name='nombre')),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'tipo de organización',
                'verbose_name_plural': 'tipos de contacto',
            },
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='tipo_contacto',
        ),
        migrations.AddField(
            model_name='contacto',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos', to='base.TipoContacto', verbose_name='tipo de contacto'),
        ),
    ]
