# Generated by Django 3.0.6 on 2020-06-29 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20200629_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocontacto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='tipoorganizacion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='descripción'),
        ),
    ]
