# Generated by Django 3.0.6 on 2020-06-07 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Necesidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_insercion', models.DateTimeField(verbose_name='fecha insercion')),
                ('descripcion', models.CharField(max_length=300, verbose_name='descripción')),
                ('ayudado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='necesidades', to='base.Persona')),
                ('lugar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='necesidades_ubicadas', to='base.Lugar')),
                ('remitente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='necesidades_ingresadas', to='base.Persona')),
            ],
            options={
                'verbose_name_plural': 'necesidades',
            },
        ),
    ]
