# Generated by Django 3.0.6 on 2020-06-21 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0005_auto_20200621_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('despacho', models.BooleanField(verbose_name='despacho')),
                ('descripcion', models.CharField(max_length=300, verbose_name='descripción')),
                ('rango', models.FloatField(verbose_name='rango')),
                ('activo', models.BooleanField(verbose_name='activo')),
                ('lugar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedores', to='base.Lugar', verbose_name='lugar')),
                ('remitente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedores', to='base.Participante', verbose_name='remitente')),
                ('tipos_gestion', models.ManyToManyField(related_name='proveedores', to='base.TipoGestion', verbose_name='tipos de gestión')),
            ],
        ),
        migrations.CreateModel(
            name='Necesidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_insercion', models.DateTimeField(verbose_name='fecha de inserción')),
                ('periodicidad', models.CharField(max_length=300, verbose_name='periodicidad')),
                ('descripcion', models.CharField(max_length=300, verbose_name='descripción')),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True, verbose_name='fecha de finalización')),
                ('estado', models.CharField(choices=[('PE', 'Pendiente'), ('AS', 'Asignada'), ('RE', 'Resuelta')], default='PE', max_length=2, verbose_name='estado')),
                ('ayudado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='necesidades', to='base.Participante', verbose_name='ayudado')),
                ('lugar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='necesidades', to='base.Lugar', verbose_name='lugar')),
                ('remitente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='necesidades_ingresadas', to='base.Participante', verbose_name='remitente')),
                ('tipo_gestion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='necesidades', to='base.TipoGestion', verbose_name='tipo de gestión')),
            ],
            options={
                'verbose_name_plural': 'necesidades',
            },
        ),
    ]
