# Generated by Django 3.0.6 on 2020-06-21 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20200621_1632'),
        ('formularios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atencionnecesidad',
            name='necesidad',
        ),
        migrations.DeleteModel(
            name='EstadoAtencionNecesidad',
        ),
        migrations.AddField(
            model_name='necesidad',
            name='estado',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('AS', 'Asignada'), ('RE', 'Resuelta')], default='PE', max_length=2, verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='necesidad',
            name='fecha_finalizacion',
            field=models.DateTimeField(default=None, verbose_name='fecha de finalización'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='necesidad',
            name='periodicidad',
            field=models.CharField(default=None, max_length=300, verbose_name='descripción'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='necesidad',
            name='tipo_gestion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='necesidades', to='base.TipoGestion', verbose_name='tipo de gestión'),
        ),
        migrations.AlterField(
            model_name='necesidad',
            name='ayudado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='necesidades', to='base.Participante', verbose_name='ayudado'),
        ),
        migrations.AlterField(
            model_name='necesidad',
            name='fecha_insercion',
            field=models.DateTimeField(verbose_name='fecha de inserción'),
        ),
        migrations.AlterField(
            model_name='necesidad',
            name='lugar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='necesidades', to='base.Lugar'),
        ),
        migrations.AlterField(
            model_name='necesidad',
            name='remitente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='necesidades_ingresadas', to='base.Participante', verbose_name='remitente'),
        ),
        migrations.DeleteModel(
            name='AtencionNecesidad',
        ),
    ]
