# Generated by Django 3.0.6 on 2020-06-23 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0002_auto_20200621_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayuda',
            name='descripcion',
            field=models.CharField(max_length=1024, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=models.CharField(max_length=1024, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='necesidad',
            name='descripcion',
            field=models.CharField(max_length=1024, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='descripcion',
            field=models.CharField(max_length=1024, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='descripcion',
            field=models.CharField(max_length=1024, verbose_name='descripción'),
        ),
    ]
