# Generated by Django 3.0.6 on 2020-06-29 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0003_auto_20200622_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlimentacionEspecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64, unique=True, verbose_name='nombre')),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'alimentación especial',
                'verbose_name_plural': 'alimentaciones especiales',
            },
        ),
        migrations.CreateModel(
            name='EstadoNecesidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64, unique=True, verbose_name='nombre')),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'estado de necesidad',
                'verbose_name_plural': 'estados de necesidad',
            },
        ),
        migrations.CreateModel(
            name='Periodicidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64, unique=True, verbose_name='nombre')),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'periodicidad',
                'verbose_name_plural': 'periodicidades',
            },
        ),
        migrations.CreateModel(
            name='TipoAyuda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=128, verbose_name='categoría')),
                ('nombre', models.CharField(max_length=128, unique=True, verbose_name='nombre')),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'tipo de ayuda',
                'verbose_name_plural': 'tipos de ayuda',
            },
        ),
        migrations.CreateModel(
            name='TipoVoluntario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=128, verbose_name='categoría')),
                ('nombre', models.CharField(max_length=128, unique=True, verbose_name='nombre')),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'tipo de voluntario',
                'verbose_name_plural': 'tipos de voluntario',
            },
        ),
        migrations.AddField(
            model_name='accion',
            name='descripcion',
            field=models.CharField(default=None, max_length=300, verbose_name='descripción'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ayuda',
            name='tiene_descripcion',
            field=models.BooleanField(blank=True, null=True, verbose_name='tiene descripción'),
        ),
        migrations.AddField(
            model_name='ayuda',
            name='tiene_estimado',
            field=models.BooleanField(blank=True, null=True, verbose_name='tiene estimado de personas que ayuda'),
        ),
        migrations.AddField(
            model_name='ayuda',
            name='tiene_material',
            field=models.BooleanField(blank=True, null=True, verbose_name='tiene material audiovisual'),
        ),
        migrations.AddField(
            model_name='necesidad',
            name='cantidad_adultos',
            field=models.IntegerField(blank=True, null=True, verbose_name='cantidad de adultos'),
        ),
        migrations.AddField(
            model_name='necesidad',
            name='cantidad_mayores',
            field=models.IntegerField(blank=True, null=True, verbose_name='cantidad de mayores'),
        ),
        migrations.AddField(
            model_name='necesidad',
            name='cantidad_menores',
            field=models.IntegerField(blank=True, null=True, verbose_name='cantidad de menores'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='alcance',
            field=models.CharField(max_length=64, null=True, verbose_name='alcance'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='mayorista',
            field=models.BooleanField(null=True, verbose_name='mayorista'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='minorista',
            field=models.BooleanField(null=True, verbose_name='minorista'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='retiro',
            field=models.BooleanField(null=True, verbose_name='retiro'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='despacho',
            field=models.BooleanField(null=True, verbose_name='despacho'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='rango',
            field=models.FloatField(null=True, verbose_name='rango'),
        ),
        migrations.AddField(
            model_name='ayuda',
            name='periodicidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ayudas', to='formularios.Periodicidad', verbose_name='periodicidad'),
        ),
        migrations.AddField(
            model_name='ayuda',
            name='tipos',
            field=models.ManyToManyField(related_name='ayudas', to='formularios.TipoAyuda', verbose_name='tipos de ayuda'),
        ),
        migrations.AddField(
            model_name='necesidad',
            name='alimentacion_especial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='necesidades', to='formularios.AlimentacionEspecial', verbose_name='alimentación especial'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='periodicidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voluntarios', to='formularios.Periodicidad', verbose_name='periodicidad'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='tipos',
            field=models.ManyToManyField(related_name='voluntarios', to='formularios.TipoVoluntario', verbose_name='tipo de voluntario'),
        ),
        migrations.AlterField(
            model_name='necesidad',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='necesidades', to='formularios.EstadoNecesidad', verbose_name='estado de necesidad'),
        ),
        migrations.AlterField(
            model_name='necesidad',
            name='periodicidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='necesidades', to='formularios.Periodicidad', verbose_name='periodicidad'),
        ),
    ]
